// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8UpoIVRs8GMPH3JIrB4BHW68tV9o4SA',
    appId: '1:115466076777:web:5e3974d59600b26cef98f8',
    messagingSenderId: '115466076777',
    projectId: 'my-chat-app-bb272',
    authDomain: 'my-chat-app-bb272.firebaseapp.com',
    storageBucket: 'my-chat-app-bb272.appspot.com',
    measurementId: 'G-CH018JSFF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_Y4NE2OjbIBVQMDYRHP8q2OOFqLJjts',
    appId: '1:115466076777:android:48d30c431032acceef98f8',
    messagingSenderId: '115466076777',
    projectId: 'my-chat-app-bb272',
    storageBucket: 'my-chat-app-bb272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVAV8D_gzVii-9Da2gY9EPqsP0eOFI5oA',
    appId: '1:115466076777:ios:ec28013d3b1b8740ef98f8',
    messagingSenderId: '115466076777',
    projectId: 'my-chat-app-bb272',
    storageBucket: 'my-chat-app-bb272.appspot.com',
    iosClientId: '115466076777-2ekjo32a08v8km2qmhseleibpc3u97ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTest',
  );
}
